version: '3'

services:
  app:
    image: timosabisch/hausaufgaben-webapp
    build: .
    ports:
      - "8001:8000"
    environment:
      - "MYSQL_PASSWORD"

  mysql:
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD"
      - "MYSQL_DATABASE=webappdb"
      - "MYSQL_USER=dbadmin"
      - "MYSQL_PASSWORD"