version: '3'

volumes:
  caddy_data:
  caddy_config:

services:
  app:
    image: timosabisch/hausaufgaben-webapp
    build: .
    ports:
      - "8001:8000"
    environment:
      - "MYSQL_PASSWORD"
      - "MYSQL_HOST"
      - "DJANGO_SETTINGS_MODULE"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD"
      - "MYSQL_DATABASE=webappdb"
      - "MYSQL_USER=dbadmin"
      - "MYSQL_PASSWORD"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 12

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from ${HOST_FQDN} --to app:8000
